package com.dimipet.jcesd;


public class View extends javax.swing.JFrame {

    /** Creates new form View */
    public View() {
        //
        initComponents();       
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonGroup0 = new javax.swing.ButtonGroup();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        buttonGroup8 = new javax.swing.ButtonGroup();
        buttonGroup9 = new javax.swing.ButtonGroup();
        buttonGroup10 = new javax.swing.ButtonGroup();
        buttonGroup11 = new javax.swing.ButtonGroup();
        buttonGroup12 = new javax.swing.ButtonGroup();
        buttonGroup13 = new javax.swing.ButtonGroup();
        buttonGroup14 = new javax.swing.ButtonGroup();
        buttonGroup15 = new javax.swing.ButtonGroup();
        buttonGroup16 = new javax.swing.ButtonGroup();
        buttonGroup17 = new javax.swing.ButtonGroup();
        buttonGroup18 = new javax.swing.ButtonGroup();
        buttonGroup19 = new javax.swing.ButtonGroup();
        mainPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel0 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        jCheckBox8 = new javax.swing.JCheckBox();
        jCheckBox9 = new javax.swing.JCheckBox();
        jCheckBox10 = new javax.swing.JCheckBox();
        jCheckBox11 = new javax.swing.JCheckBox();
        jCheckBox12 = new javax.swing.JCheckBox();
        jCheckBox13 = new javax.swing.JCheckBox();
        jCheckBox14 = new javax.swing.JCheckBox();
        jCheckBox15 = new javax.swing.JCheckBox();
        jCheckBox16 = new javax.swing.JCheckBox();
        jCheckBox17 = new javax.swing.JCheckBox();
        jCheckBox18 = new javax.swing.JCheckBox();
        jCheckBox19 = new javax.swing.JCheckBox();
        jCheckBox20 = new javax.swing.JCheckBox();
        jCheckBox21 = new javax.swing.JCheckBox();
        jCheckBox22 = new javax.swing.JCheckBox();
        jCheckBox23 = new javax.swing.JCheckBox();
        jCheckBox24 = new javax.swing.JCheckBox();
        jCheckBox25 = new javax.swing.JCheckBox();
        jCheckBox26 = new javax.swing.JCheckBox();
        jCheckBox27 = new javax.swing.JCheckBox();
        jCheckBox28 = new javax.swing.JCheckBox();
        jCheckBox29 = new javax.swing.JCheckBox();
        jCheckBox30 = new javax.swing.JCheckBox();
        jCheckBox31 = new javax.swing.JCheckBox();
        jCheckBox32 = new javax.swing.JCheckBox();
        jCheckBox33 = new javax.swing.JCheckBox();
        jCheckBox34 = new javax.swing.JCheckBox();
        jCheckBox35 = new javax.swing.JCheckBox();
        jCheckBox36 = new javax.swing.JCheckBox();
        jCheckBox37 = new javax.swing.JCheckBox();
        jCheckBox38 = new javax.swing.JCheckBox();
        jCheckBox39 = new javax.swing.JCheckBox();
        jCheckBox40 = new javax.swing.JCheckBox();
        jCheckBox41 = new javax.swing.JCheckBox();
        jCheckBox42 = new javax.swing.JCheckBox();
        jCheckBox43 = new javax.swing.JCheckBox();
        jCheckBox44 = new javax.swing.JCheckBox();
        jCheckBox45 = new javax.swing.JCheckBox();
        jCheckBox46 = new javax.swing.JCheckBox();
        jCheckBox47 = new javax.swing.JCheckBox();
        jCheckBox48 = new javax.swing.JCheckBox();
        jCheckBox49 = new javax.swing.JCheckBox();
        jCheckBox50 = new javax.swing.JCheckBox();
        jCheckBox51 = new javax.swing.JCheckBox();
        jCheckBox52 = new javax.swing.JCheckBox();
        jCheckBox53 = new javax.swing.JCheckBox();
        jCheckBox54 = new javax.swing.JCheckBox();
        jCheckBox55 = new javax.swing.JCheckBox();
        jCheckBox56 = new javax.swing.JCheckBox();
        jCheckBox57 = new javax.swing.JCheckBox();
        jCheckBox58 = new javax.swing.JCheckBox();
        jCheckBox59 = new javax.swing.JCheckBox();
        jCheckBox60 = new javax.swing.JCheckBox();
        jCheckBox61 = new javax.swing.JCheckBox();
        jCheckBox62 = new javax.swing.JCheckBox();
        jCheckBox63 = new javax.swing.JCheckBox();
        jCheckBox64 = new javax.swing.JCheckBox();
        jCheckBox65 = new javax.swing.JCheckBox();
        jCheckBox66 = new javax.swing.JCheckBox();
        jCheckBox67 = new javax.swing.JCheckBox();
        jCheckBox68 = new javax.swing.JCheckBox();
        jCheckBox69 = new javax.swing.JCheckBox();
        jCheckBox70 = new javax.swing.JCheckBox();
        jCheckBox71 = new javax.swing.JCheckBox();
        jCheckBox72 = new javax.swing.JCheckBox();
        jCheckBox73 = new javax.swing.JCheckBox();
        jCheckBox74 = new javax.swing.JCheckBox();
        jCheckBox75 = new javax.swing.JCheckBox();
        jCheckBox76 = new javax.swing.JCheckBox();
        jCheckBox77 = new javax.swing.JCheckBox();
        jCheckBox78 = new javax.swing.JCheckBox();
        jCheckBox79 = new javax.swing.JCheckBox();
        jCheckBox0 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Form"); // NOI18N
        getContentPane().setLayout(new java.awt.GridBagLayout());

        mainPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(-16777216,true)));
        mainPanel.setName("mainPanel"); // NOI18N
        mainPanel.setLayout(new java.awt.GridBagLayout());

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(com.dimipet.jcesd.JCESDApp.class).getContext().getResourceMap(View.class);
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        mainPanel.add(jLabel1, gridBagConstraints);

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        mainPanel.add(jLabel2, gridBagConstraints);

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        mainPanel.add(jLabel3, gridBagConstraints);

        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        mainPanel.add(jLabel4, gridBagConstraints);

        jLabel5.setText(resourceMap.getString("jLabel5.text")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        mainPanel.add(jLabel5, gridBagConstraints);

        jLabel6.setText(resourceMap.getString("jLabel6.text")); // NOI18N
        jLabel6.setName("jLabel6"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        mainPanel.add(jLabel6, gridBagConstraints);

        jLabel7.setText(resourceMap.getString("jLabel7.text")); // NOI18N
        jLabel7.setName("jLabel7"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        mainPanel.add(jLabel7, gridBagConstraints);

        jLabel8.setText(resourceMap.getString("jLabel8.text")); // NOI18N
        jLabel8.setName("jLabel8"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        mainPanel.add(jLabel8, gridBagConstraints);

        jLabel9.setText(resourceMap.getString("jLabel9.text")); // NOI18N
        jLabel9.setName("jLabel9"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        mainPanel.add(jLabel9, gridBagConstraints);

        jLabel10.setText(resourceMap.getString("jLabel10.text")); // NOI18N
        jLabel10.setName("jLabel10"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        mainPanel.add(jLabel10, gridBagConstraints);

        jLabel11.setText(resourceMap.getString("jLabel11.text")); // NOI18N
        jLabel11.setName("jLabel11"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 11;
        mainPanel.add(jLabel11, gridBagConstraints);

        jLabel12.setText(resourceMap.getString("jLabel12.text")); // NOI18N
        jLabel12.setName("jLabel12"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        mainPanel.add(jLabel12, gridBagConstraints);

        jLabel13.setText(resourceMap.getString("jLabel13.text")); // NOI18N
        jLabel13.setName("jLabel13"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 13;
        mainPanel.add(jLabel13, gridBagConstraints);

        jLabel14.setText(resourceMap.getString("jLabel14.text")); // NOI18N
        jLabel14.setName("jLabel14"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 14;
        mainPanel.add(jLabel14, gridBagConstraints);

        jLabel15.setText(resourceMap.getString("jLabel15.text")); // NOI18N
        jLabel15.setName("jLabel15"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 15;
        mainPanel.add(jLabel15, gridBagConstraints);

        jLabel16.setText(resourceMap.getString("jLabel16.text")); // NOI18N
        jLabel16.setName("jLabel16"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 16;
        mainPanel.add(jLabel16, gridBagConstraints);

        jLabel17.setText(resourceMap.getString("jLabel17.text")); // NOI18N
        jLabel17.setName("jLabel17"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 17;
        mainPanel.add(jLabel17, gridBagConstraints);

        jLabel18.setText(resourceMap.getString("jLabel18.text")); // NOI18N
        jLabel18.setName("jLabel18"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 18;
        mainPanel.add(jLabel18, gridBagConstraints);

        jLabel19.setText(resourceMap.getString("jLabel19.text")); // NOI18N
        jLabel19.setName("jLabel19"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 19;
        mainPanel.add(jLabel19, gridBagConstraints);

        jLabel0.setText(resourceMap.getString("jLabel0.text")); // NOI18N
        jLabel0.setName("jLabel0"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        mainPanel.add(jLabel0, gridBagConstraints);
        jLabel0.getAccessibleContext().setAccessibleName(resourceMap.getString("jLabel0.AccessibleContext.accessibleName")); // NOI18N

        buttonGroup0.add(jCheckBox1);
        jCheckBox1.setLabel(resourceMap.getString("jCheckBox1.label")); // NOI18N
        jCheckBox1.setName("jCheckBox1"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        mainPanel.add(jCheckBox1, gridBagConstraints);

        buttonGroup0.add(jCheckBox2);
        jCheckBox2.setLabel(resourceMap.getString("jCheckBox2.label")); // NOI18N
        jCheckBox2.setName("jCheckBox2"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        mainPanel.add(jCheckBox2, gridBagConstraints);

        buttonGroup0.add(jCheckBox3);
        jCheckBox3.setLabel(resourceMap.getString("jCheckBox3.label")); // NOI18N
        jCheckBox3.setName("jCheckBox3"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        mainPanel.add(jCheckBox3, gridBagConstraints);

        buttonGroup1.add(jCheckBox4);
        jCheckBox4.setLabel(resourceMap.getString("jCheckBox4.label")); // NOI18N
        jCheckBox4.setName("jCheckBox4"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        mainPanel.add(jCheckBox4, gridBagConstraints);

        buttonGroup1.add(jCheckBox5);
        jCheckBox5.setLabel(resourceMap.getString("jCheckBox5.label")); // NOI18N
        jCheckBox5.setName("jCheckBox5"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        mainPanel.add(jCheckBox5, gridBagConstraints);

        buttonGroup1.add(jCheckBox6);
        jCheckBox6.setLabel(resourceMap.getString("jCheckBox6.label")); // NOI18N
        jCheckBox6.setName("jCheckBox6"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        mainPanel.add(jCheckBox6, gridBagConstraints);

        buttonGroup1.add(jCheckBox7);
        jCheckBox7.setLabel(resourceMap.getString("jCheckBox7.label")); // NOI18N
        jCheckBox7.setName("jCheckBox7"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        mainPanel.add(jCheckBox7, gridBagConstraints);

        buttonGroup2.add(jCheckBox8);
        jCheckBox8.setLabel(resourceMap.getString("jCheckBox8.label")); // NOI18N
        jCheckBox8.setName("jCheckBox8"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        mainPanel.add(jCheckBox8, gridBagConstraints);

        buttonGroup2.add(jCheckBox9);
        jCheckBox9.setLabel(resourceMap.getString("jCheckBox9.label")); // NOI18N
        jCheckBox9.setName("jCheckBox9"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        mainPanel.add(jCheckBox9, gridBagConstraints);

        buttonGroup2.add(jCheckBox10);
        jCheckBox10.setLabel(resourceMap.getString("jCheckBox10.label")); // NOI18N
        jCheckBox10.setName("jCheckBox10"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        mainPanel.add(jCheckBox10, gridBagConstraints);

        buttonGroup2.add(jCheckBox11);
        jCheckBox11.setLabel(resourceMap.getString("jCheckBox11.label")); // NOI18N
        jCheckBox11.setName("jCheckBox11"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        mainPanel.add(jCheckBox11, gridBagConstraints);

        buttonGroup3.add(jCheckBox12);
        jCheckBox12.setLabel(resourceMap.getString("jCheckBox12.label")); // NOI18N
        jCheckBox12.setName("jCheckBox12"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        mainPanel.add(jCheckBox12, gridBagConstraints);

        buttonGroup3.add(jCheckBox13);
        jCheckBox13.setLabel(resourceMap.getString("jCheckBox13.label")); // NOI18N
        jCheckBox13.setName("jCheckBox13"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        mainPanel.add(jCheckBox13, gridBagConstraints);

        buttonGroup3.add(jCheckBox14);
        jCheckBox14.setLabel(resourceMap.getString("jCheckBox14.label")); // NOI18N
        jCheckBox14.setName("jCheckBox14"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        mainPanel.add(jCheckBox14, gridBagConstraints);

        buttonGroup3.add(jCheckBox15);
        jCheckBox15.setLabel(resourceMap.getString("jCheckBox15.label")); // NOI18N
        jCheckBox15.setName("jCheckBox15"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 3;
        mainPanel.add(jCheckBox15, gridBagConstraints);

        buttonGroup4.add(jCheckBox16);
        jCheckBox16.setLabel(resourceMap.getString("jCheckBox16.label")); // NOI18N
        jCheckBox16.setName("jCheckBox16"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        mainPanel.add(jCheckBox16, gridBagConstraints);

        buttonGroup4.add(jCheckBox17);
        jCheckBox17.setLabel(resourceMap.getString("jCheckBox17.label")); // NOI18N
        jCheckBox17.setName("jCheckBox17"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        mainPanel.add(jCheckBox17, gridBagConstraints);

        buttonGroup4.add(jCheckBox18);
        jCheckBox18.setLabel(resourceMap.getString("jCheckBox18.label")); // NOI18N
        jCheckBox18.setName("jCheckBox18"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        mainPanel.add(jCheckBox18, gridBagConstraints);

        buttonGroup4.add(jCheckBox19);
        jCheckBox19.setLabel(resourceMap.getString("jCheckBox19.label")); // NOI18N
        jCheckBox19.setName("jCheckBox19"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 4;
        mainPanel.add(jCheckBox19, gridBagConstraints);

        buttonGroup5.add(jCheckBox20);
        jCheckBox20.setLabel(resourceMap.getString("jCheckBox20.label")); // NOI18N
        jCheckBox20.setName("jCheckBox20"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        mainPanel.add(jCheckBox20, gridBagConstraints);

        buttonGroup5.add(jCheckBox21);
        jCheckBox21.setLabel(resourceMap.getString("jCheckBox21.label")); // NOI18N
        jCheckBox21.setName("jCheckBox21"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        mainPanel.add(jCheckBox21, gridBagConstraints);

        buttonGroup5.add(jCheckBox22);
        jCheckBox22.setLabel(resourceMap.getString("jCheckBox22.label")); // NOI18N
        jCheckBox22.setName("jCheckBox22"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 5;
        mainPanel.add(jCheckBox22, gridBagConstraints);

        buttonGroup5.add(jCheckBox23);
        jCheckBox23.setLabel(resourceMap.getString("jCheckBox23.label")); // NOI18N
        jCheckBox23.setName("jCheckBox23"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 5;
        mainPanel.add(jCheckBox23, gridBagConstraints);

        buttonGroup6.add(jCheckBox24);
        jCheckBox24.setLabel(resourceMap.getString("jCheckBox24.label")); // NOI18N
        jCheckBox24.setName("jCheckBox24"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        mainPanel.add(jCheckBox24, gridBagConstraints);

        buttonGroup6.add(jCheckBox25);
        jCheckBox25.setLabel(resourceMap.getString("jCheckBox25.label")); // NOI18N
        jCheckBox25.setName("jCheckBox25"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        mainPanel.add(jCheckBox25, gridBagConstraints);

        buttonGroup6.add(jCheckBox26);
        jCheckBox26.setLabel(resourceMap.getString("jCheckBox26.label")); // NOI18N
        jCheckBox26.setName("jCheckBox26"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 6;
        mainPanel.add(jCheckBox26, gridBagConstraints);

        buttonGroup6.add(jCheckBox27);
        jCheckBox27.setLabel(resourceMap.getString("jCheckBox27.label")); // NOI18N
        jCheckBox27.setName("jCheckBox27"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 6;
        mainPanel.add(jCheckBox27, gridBagConstraints);

        buttonGroup7.add(jCheckBox28);
        jCheckBox28.setLabel(resourceMap.getString("jCheckBox28.label")); // NOI18N
        jCheckBox28.setName("jCheckBox28"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        mainPanel.add(jCheckBox28, gridBagConstraints);

        buttonGroup7.add(jCheckBox29);
        jCheckBox29.setLabel(resourceMap.getString("jCheckBox29.label")); // NOI18N
        jCheckBox29.setName("jCheckBox29"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 7;
        mainPanel.add(jCheckBox29, gridBagConstraints);

        buttonGroup7.add(jCheckBox30);
        jCheckBox30.setLabel(resourceMap.getString("jCheckBox30.label")); // NOI18N
        jCheckBox30.setName("jCheckBox30"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 7;
        mainPanel.add(jCheckBox30, gridBagConstraints);

        buttonGroup7.add(jCheckBox31);
        jCheckBox31.setLabel(resourceMap.getString("jCheckBox31.label")); // NOI18N
        jCheckBox31.setName("jCheckBox31"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 7;
        mainPanel.add(jCheckBox31, gridBagConstraints);

        buttonGroup8.add(jCheckBox32);
        jCheckBox32.setLabel(resourceMap.getString("jCheckBox32.label")); // NOI18N
        jCheckBox32.setName("jCheckBox32"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        mainPanel.add(jCheckBox32, gridBagConstraints);

        buttonGroup8.add(jCheckBox33);
        jCheckBox33.setLabel(resourceMap.getString("jCheckBox33.label")); // NOI18N
        jCheckBox33.setName("jCheckBox33"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        mainPanel.add(jCheckBox33, gridBagConstraints);

        buttonGroup8.add(jCheckBox34);
        jCheckBox34.setLabel(resourceMap.getString("jCheckBox34.label")); // NOI18N
        jCheckBox34.setName("jCheckBox34"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 8;
        mainPanel.add(jCheckBox34, gridBagConstraints);

        buttonGroup8.add(jCheckBox35);
        jCheckBox35.setLabel(resourceMap.getString("jCheckBox35.label")); // NOI18N
        jCheckBox35.setName("jCheckBox35"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 8;
        mainPanel.add(jCheckBox35, gridBagConstraints);

        buttonGroup9.add(jCheckBox36);
        jCheckBox36.setLabel(resourceMap.getString("jCheckBox36.label")); // NOI18N
        jCheckBox36.setName("jCheckBox36"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 9;
        mainPanel.add(jCheckBox36, gridBagConstraints);

        buttonGroup9.add(jCheckBox37);
        jCheckBox37.setLabel(resourceMap.getString("jCheckBox37.label")); // NOI18N
        jCheckBox37.setName("jCheckBox37"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 9;
        mainPanel.add(jCheckBox37, gridBagConstraints);

        buttonGroup9.add(jCheckBox38);
        jCheckBox38.setLabel(resourceMap.getString("jCheckBox38.label")); // NOI18N
        jCheckBox38.setName("jCheckBox38"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 9;
        mainPanel.add(jCheckBox38, gridBagConstraints);

        buttonGroup9.add(jCheckBox39);
        jCheckBox39.setLabel(resourceMap.getString("jCheckBox39.label")); // NOI18N
        jCheckBox39.setName("jCheckBox39"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 9;
        mainPanel.add(jCheckBox39, gridBagConstraints);

        buttonGroup10.add(jCheckBox40);
        jCheckBox40.setLabel(resourceMap.getString("jCheckBox40.label")); // NOI18N
        jCheckBox40.setName("jCheckBox40"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 10;
        mainPanel.add(jCheckBox40, gridBagConstraints);

        buttonGroup10.add(jCheckBox41);
        jCheckBox41.setLabel(resourceMap.getString("jCheckBox41.label")); // NOI18N
        jCheckBox41.setName("jCheckBox41"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 10;
        mainPanel.add(jCheckBox41, gridBagConstraints);

        buttonGroup10.add(jCheckBox42);
        jCheckBox42.setLabel(resourceMap.getString("jCheckBox42.label")); // NOI18N
        jCheckBox42.setName("jCheckBox42"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 10;
        mainPanel.add(jCheckBox42, gridBagConstraints);

        buttonGroup10.add(jCheckBox43);
        jCheckBox43.setLabel(resourceMap.getString("jCheckBox43.label")); // NOI18N
        jCheckBox43.setName("jCheckBox43"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 10;
        mainPanel.add(jCheckBox43, gridBagConstraints);

        buttonGroup11.add(jCheckBox44);
        jCheckBox44.setLabel(resourceMap.getString("jCheckBox44.label")); // NOI18N
        jCheckBox44.setName("jCheckBox44"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 11;
        mainPanel.add(jCheckBox44, gridBagConstraints);

        buttonGroup11.add(jCheckBox45);
        jCheckBox45.setLabel(resourceMap.getString("jCheckBox45.label")); // NOI18N
        jCheckBox45.setName("jCheckBox45"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 11;
        mainPanel.add(jCheckBox45, gridBagConstraints);

        buttonGroup11.add(jCheckBox46);
        jCheckBox46.setLabel(resourceMap.getString("jCheckBox46.label")); // NOI18N
        jCheckBox46.setName("jCheckBox46"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 11;
        mainPanel.add(jCheckBox46, gridBagConstraints);

        buttonGroup11.add(jCheckBox47);
        jCheckBox47.setLabel(resourceMap.getString("jCheckBox47.label")); // NOI18N
        jCheckBox47.setName("jCheckBox47"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 11;
        mainPanel.add(jCheckBox47, gridBagConstraints);

        buttonGroup12.add(jCheckBox48);
        jCheckBox48.setLabel(resourceMap.getString("jCheckBox48.label")); // NOI18N
        jCheckBox48.setName("jCheckBox48"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 12;
        mainPanel.add(jCheckBox48, gridBagConstraints);

        buttonGroup12.add(jCheckBox49);
        jCheckBox49.setLabel(resourceMap.getString("jCheckBox49.label")); // NOI18N
        jCheckBox49.setName("jCheckBox49"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 12;
        mainPanel.add(jCheckBox49, gridBagConstraints);

        buttonGroup12.add(jCheckBox50);
        jCheckBox50.setLabel(resourceMap.getString("jCheckBox50.label")); // NOI18N
        jCheckBox50.setName("jCheckBox50"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 12;
        mainPanel.add(jCheckBox50, gridBagConstraints);

        buttonGroup12.add(jCheckBox51);
        jCheckBox51.setLabel(resourceMap.getString("jCheckBox51.label")); // NOI18N
        jCheckBox51.setName("jCheckBox51"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 12;
        mainPanel.add(jCheckBox51, gridBagConstraints);

        buttonGroup13.add(jCheckBox52);
        jCheckBox52.setLabel(resourceMap.getString("jCheckBox52.label")); // NOI18N
        jCheckBox52.setName("jCheckBox52"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 13;
        mainPanel.add(jCheckBox52, gridBagConstraints);

        buttonGroup13.add(jCheckBox53);
        jCheckBox53.setLabel(resourceMap.getString("jCheckBox53.label")); // NOI18N
        jCheckBox53.setName("jCheckBox53"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 13;
        mainPanel.add(jCheckBox53, gridBagConstraints);

        buttonGroup13.add(jCheckBox54);
        jCheckBox54.setLabel(resourceMap.getString("jCheckBox54.label")); // NOI18N
        jCheckBox54.setName("jCheckBox54"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 13;
        mainPanel.add(jCheckBox54, gridBagConstraints);

        buttonGroup13.add(jCheckBox55);
        jCheckBox55.setLabel(resourceMap.getString("jCheckBox55.label")); // NOI18N
        jCheckBox55.setName("jCheckBox55"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 13;
        mainPanel.add(jCheckBox55, gridBagConstraints);

        buttonGroup14.add(jCheckBox56);
        jCheckBox56.setLabel(resourceMap.getString("jCheckBox56.label")); // NOI18N
        jCheckBox56.setName("jCheckBox56"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 14;
        mainPanel.add(jCheckBox56, gridBagConstraints);

        buttonGroup14.add(jCheckBox57);
        jCheckBox57.setLabel(resourceMap.getString("jCheckBox57.label")); // NOI18N
        jCheckBox57.setName("jCheckBox57"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 14;
        mainPanel.add(jCheckBox57, gridBagConstraints);

        buttonGroup14.add(jCheckBox58);
        jCheckBox58.setLabel(resourceMap.getString("jCheckBox58.label")); // NOI18N
        jCheckBox58.setName("jCheckBox58"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 14;
        mainPanel.add(jCheckBox58, gridBagConstraints);

        buttonGroup14.add(jCheckBox59);
        jCheckBox59.setLabel(resourceMap.getString("jCheckBox59.label")); // NOI18N
        jCheckBox59.setName("jCheckBox59"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 14;
        mainPanel.add(jCheckBox59, gridBagConstraints);

        buttonGroup15.add(jCheckBox60);
        jCheckBox60.setLabel(resourceMap.getString("jCheckBox60.label")); // NOI18N
        jCheckBox60.setName("jCheckBox60"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 15;
        mainPanel.add(jCheckBox60, gridBagConstraints);

        buttonGroup15.add(jCheckBox61);
        jCheckBox61.setLabel(resourceMap.getString("jCheckBox61.label")); // NOI18N
        jCheckBox61.setName("jCheckBox61"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 15;
        mainPanel.add(jCheckBox61, gridBagConstraints);

        buttonGroup15.add(jCheckBox62);
        jCheckBox62.setLabel(resourceMap.getString("jCheckBox62.label")); // NOI18N
        jCheckBox62.setName("jCheckBox62"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 15;
        mainPanel.add(jCheckBox62, gridBagConstraints);

        buttonGroup15.add(jCheckBox63);
        jCheckBox63.setLabel(resourceMap.getString("jCheckBox63.label")); // NOI18N
        jCheckBox63.setName("jCheckBox63"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 15;
        mainPanel.add(jCheckBox63, gridBagConstraints);

        buttonGroup16.add(jCheckBox64);
        jCheckBox64.setLabel(resourceMap.getString("jCheckBox64.label")); // NOI18N
        jCheckBox64.setName("jCheckBox64"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 16;
        mainPanel.add(jCheckBox64, gridBagConstraints);

        buttonGroup16.add(jCheckBox65);
        jCheckBox65.setLabel(resourceMap.getString("jCheckBox65.label")); // NOI18N
        jCheckBox65.setName("jCheckBox65"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 16;
        mainPanel.add(jCheckBox65, gridBagConstraints);

        buttonGroup16.add(jCheckBox66);
        jCheckBox66.setLabel(resourceMap.getString("jCheckBox66.label")); // NOI18N
        jCheckBox66.setName("jCheckBox66"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 16;
        mainPanel.add(jCheckBox66, gridBagConstraints);

        buttonGroup16.add(jCheckBox67);
        jCheckBox67.setLabel(resourceMap.getString("jCheckBox67.label")); // NOI18N
        jCheckBox67.setName("jCheckBox67"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 16;
        mainPanel.add(jCheckBox67, gridBagConstraints);

        buttonGroup17.add(jCheckBox68);
        jCheckBox68.setLabel(resourceMap.getString("jCheckBox68.label")); // NOI18N
        jCheckBox68.setName("jCheckBox68"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 17;
        mainPanel.add(jCheckBox68, gridBagConstraints);

        buttonGroup17.add(jCheckBox69);
        jCheckBox69.setLabel(resourceMap.getString("jCheckBox69.label")); // NOI18N
        jCheckBox69.setName("jCheckBox69"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 17;
        mainPanel.add(jCheckBox69, gridBagConstraints);

        buttonGroup17.add(jCheckBox70);
        jCheckBox70.setLabel(resourceMap.getString("jCheckBox70.label")); // NOI18N
        jCheckBox70.setName("jCheckBox70"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 17;
        mainPanel.add(jCheckBox70, gridBagConstraints);

        buttonGroup17.add(jCheckBox71);
        jCheckBox71.setLabel(resourceMap.getString("jCheckBox71.label")); // NOI18N
        jCheckBox71.setName("jCheckBox71"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 17;
        mainPanel.add(jCheckBox71, gridBagConstraints);

        buttonGroup18.add(jCheckBox72);
        jCheckBox72.setLabel(resourceMap.getString("jCheckBox72.label")); // NOI18N
        jCheckBox72.setName("jCheckBox72"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 18;
        mainPanel.add(jCheckBox72, gridBagConstraints);

        buttonGroup18.add(jCheckBox73);
        jCheckBox73.setLabel(resourceMap.getString("jCheckBox73.label")); // NOI18N
        jCheckBox73.setName("jCheckBox73"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 18;
        mainPanel.add(jCheckBox73, gridBagConstraints);

        buttonGroup18.add(jCheckBox74);
        jCheckBox74.setLabel(resourceMap.getString("jCheckBox74.label")); // NOI18N
        jCheckBox74.setName("jCheckBox74"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 18;
        mainPanel.add(jCheckBox74, gridBagConstraints);

        buttonGroup18.add(jCheckBox75);
        jCheckBox75.setLabel(resourceMap.getString("jCheckBox75.label")); // NOI18N
        jCheckBox75.setName("jCheckBox75"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 18;
        mainPanel.add(jCheckBox75, gridBagConstraints);

        buttonGroup19.add(jCheckBox76);
        jCheckBox76.setLabel(resourceMap.getString("jCheckBox76.label")); // NOI18N
        jCheckBox76.setName("jCheckBox76"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 19;
        mainPanel.add(jCheckBox76, gridBagConstraints);

        buttonGroup19.add(jCheckBox77);
        jCheckBox77.setLabel(resourceMap.getString("jCheckBox77.label")); // NOI18N
        jCheckBox77.setName("jCheckBox77"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 19;
        mainPanel.add(jCheckBox77, gridBagConstraints);

        buttonGroup19.add(jCheckBox78);
        jCheckBox78.setLabel(resourceMap.getString("jCheckBox78.label")); // NOI18N
        jCheckBox78.setName("jCheckBox78"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 19;
        mainPanel.add(jCheckBox78, gridBagConstraints);

        buttonGroup19.add(jCheckBox79);
        jCheckBox79.setLabel(resourceMap.getString("jCheckBox79.label")); // NOI18N
        jCheckBox79.setName("jCheckBox79"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 19;
        mainPanel.add(jCheckBox79, gridBagConstraints);

        buttonGroup0.add(jCheckBox0);
        jCheckBox0.setLabel(resourceMap.getString("jCheckBox0.label")); // NOI18N
        jCheckBox0.setName("jCheckBox0"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        mainPanel.add(jCheckBox0, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        getContentPane().add(mainPanel, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new View().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup0;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup10;
    private javax.swing.ButtonGroup buttonGroup11;
    private javax.swing.ButtonGroup buttonGroup12;
    private javax.swing.ButtonGroup buttonGroup13;
    private javax.swing.ButtonGroup buttonGroup14;
    private javax.swing.ButtonGroup buttonGroup15;
    private javax.swing.ButtonGroup buttonGroup16;
    private javax.swing.ButtonGroup buttonGroup17;
    private javax.swing.ButtonGroup buttonGroup18;
    private javax.swing.ButtonGroup buttonGroup19;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.ButtonGroup buttonGroup8;
    private javax.swing.ButtonGroup buttonGroup9;
    private javax.swing.JCheckBox jCheckBox0;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox10;
    private javax.swing.JCheckBox jCheckBox11;
    private javax.swing.JCheckBox jCheckBox12;
    private javax.swing.JCheckBox jCheckBox13;
    private javax.swing.JCheckBox jCheckBox14;
    private javax.swing.JCheckBox jCheckBox15;
    private javax.swing.JCheckBox jCheckBox16;
    private javax.swing.JCheckBox jCheckBox17;
    private javax.swing.JCheckBox jCheckBox18;
    private javax.swing.JCheckBox jCheckBox19;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox20;
    private javax.swing.JCheckBox jCheckBox21;
    private javax.swing.JCheckBox jCheckBox22;
    private javax.swing.JCheckBox jCheckBox23;
    private javax.swing.JCheckBox jCheckBox24;
    private javax.swing.JCheckBox jCheckBox25;
    private javax.swing.JCheckBox jCheckBox26;
    private javax.swing.JCheckBox jCheckBox27;
    private javax.swing.JCheckBox jCheckBox28;
    private javax.swing.JCheckBox jCheckBox29;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox30;
    private javax.swing.JCheckBox jCheckBox31;
    private javax.swing.JCheckBox jCheckBox32;
    private javax.swing.JCheckBox jCheckBox33;
    private javax.swing.JCheckBox jCheckBox34;
    private javax.swing.JCheckBox jCheckBox35;
    private javax.swing.JCheckBox jCheckBox36;
    private javax.swing.JCheckBox jCheckBox37;
    private javax.swing.JCheckBox jCheckBox38;
    private javax.swing.JCheckBox jCheckBox39;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox40;
    private javax.swing.JCheckBox jCheckBox41;
    private javax.swing.JCheckBox jCheckBox42;
    private javax.swing.JCheckBox jCheckBox43;
    private javax.swing.JCheckBox jCheckBox44;
    private javax.swing.JCheckBox jCheckBox45;
    private javax.swing.JCheckBox jCheckBox46;
    private javax.swing.JCheckBox jCheckBox47;
    private javax.swing.JCheckBox jCheckBox48;
    private javax.swing.JCheckBox jCheckBox49;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox50;
    private javax.swing.JCheckBox jCheckBox51;
    private javax.swing.JCheckBox jCheckBox52;
    private javax.swing.JCheckBox jCheckBox53;
    private javax.swing.JCheckBox jCheckBox54;
    private javax.swing.JCheckBox jCheckBox55;
    private javax.swing.JCheckBox jCheckBox56;
    private javax.swing.JCheckBox jCheckBox57;
    private javax.swing.JCheckBox jCheckBox58;
    private javax.swing.JCheckBox jCheckBox59;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox60;
    private javax.swing.JCheckBox jCheckBox61;
    private javax.swing.JCheckBox jCheckBox62;
    private javax.swing.JCheckBox jCheckBox63;
    private javax.swing.JCheckBox jCheckBox64;
    private javax.swing.JCheckBox jCheckBox65;
    private javax.swing.JCheckBox jCheckBox66;
    private javax.swing.JCheckBox jCheckBox67;
    private javax.swing.JCheckBox jCheckBox68;
    private javax.swing.JCheckBox jCheckBox69;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JCheckBox jCheckBox70;
    private javax.swing.JCheckBox jCheckBox71;
    private javax.swing.JCheckBox jCheckBox72;
    private javax.swing.JCheckBox jCheckBox73;
    private javax.swing.JCheckBox jCheckBox74;
    private javax.swing.JCheckBox jCheckBox75;
    private javax.swing.JCheckBox jCheckBox76;
    private javax.swing.JCheckBox jCheckBox77;
    private javax.swing.JCheckBox jCheckBox78;
    private javax.swing.JCheckBox jCheckBox79;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JCheckBox jCheckBox9;
    private javax.swing.JLabel jLabel0;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel mainPanel;
    // End of variables declaration//GEN-END:variables
}
